sudo: required
dist: trusty
language: ruby

rvm:
- "2.1.9"
- "2.2.5"
- "2.3.1"

services:
- docker

cache:
  bundler: true
  directories:
  - /var/lib/docker

script:
- docker version
- kitchen --version
- rake spec
- kitchen test -d always
