dist: xenial
language: ruby

rvm:
- 2.3.8
- 2.4.5
- 2.5.3
- 2.6.0

services:
- docker

script:
- bundle exec docker version
- bundle exec kitchen --version
- bundle exec rake spec
- bundle exec kitchen test -d always
